/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmsproject;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author anushkatrivedi
 */
public class InsertForm extends javax.swing.JFrame {
    public InsertForm() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(174, 198, 207));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertEmployee = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        InsertEmployee1 = new javax.swing.JButton();
        CompanyBtn = new javax.swing.JButton();
        BranchBtn = new javax.swing.JButton();
        SalaryBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InsertEmployee.setBackground(new java.awt.Color(255, 228, 196));
        InsertEmployee.setText("Employee");
        InsertEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertEmployeeActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(255, 228, 196));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        InsertEmployee1.setBackground(new java.awt.Color(255, 228, 196));
        InsertEmployee1.setText("Employer");
        InsertEmployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertEmployee1ActionPerformed(evt);
            }
        });

        CompanyBtn.setBackground(new java.awt.Color(255, 228, 196));
        CompanyBtn.setText("Company");
        CompanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyBtnActionPerformed(evt);
            }
        });

        BranchBtn.setBackground(new java.awt.Color(255, 228, 196));
        BranchBtn.setText("Branch");
        BranchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchBtnActionPerformed(evt);
            }
        });

        SalaryBTN.setBackground(new java.awt.Color(255, 228, 196));
        SalaryBTN.setText("Salary");
        SalaryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 0, 0));
        jLabel1.setText("Where do you wish to insert?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InsertEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InsertEmployee1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CompanyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BranchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SalaryBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(BackBtn)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(InsertEmployee)
                .addGap(18, 18, 18)
                .addComponent(InsertEmployee1)
                .addGap(18, 18, 18)
                .addComponent(CompanyBtn)
                .addGap(18, 18, 18)
                .addComponent(BranchBtn)
                .addGap(18, 18, 18)
                .addComponent(SalaryBTN)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertEmployeeActionPerformed
        InsertEmployeeForm ief = new InsertEmployeeForm();
        ief.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_InsertEmployeeActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        HomePageForm hpgf = new HomePageForm();
        setVisible(false);
        hpgf.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void InsertEmployee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertEmployee1ActionPerformed
        InsertEmployerForm ief = new InsertEmployerForm();
        setVisible(false);
        ief.setVisible(true);
    }//GEN-LAST:event_InsertEmployee1ActionPerformed

    private void CompanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyBtnActionPerformed
        InsertCompanyForm icf = new InsertCompanyForm();
        setVisible(false);
        icf.setVisible(true);
    }//GEN-LAST:event_CompanyBtnActionPerformed

    private void BranchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchBtnActionPerformed
        InsertBranchForm ibf = new InsertBranchForm();
        setVisible(false);
        ibf.setVisible(true);
    }//GEN-LAST:event_BranchBtnActionPerformed

    private void SalaryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryBTNActionPerformed
        InsertSalaryForm isf = new InsertSalaryForm();
        setVisible(false);
        isf.setVisible(true);
    }//GEN-LAST:event_SalaryBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BranchBtn;
    private javax.swing.JButton CompanyBtn;
    private javax.swing.JButton InsertEmployee;
    private javax.swing.JButton InsertEmployee1;
    private javax.swing.JButton SalaryBTN;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
